In [1]:
import numpy as np
#NumPy is the fundamental package for scientific computing in Python. 
#It is a Python library that provides a multidimensional array object, 
#various derived objects (such as masked arrays and matrices), 
#and an assortment of routines for fast operations on arrays, 
#including mathematical, logical, shape manipulation, sorting, 
#selecting, I/O, discrete Fourier transforms, basic linear algebra, 
#basic statistical operations, random simulation and much more./*

In [2]:
#Function One
#add is used for concatenation of array

#1
np.char.add(["I don't", "ple"],[' want to do this', 'ase'])

#2
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
b=np.insert(a, 1, 5)
print(b)

[[1 1]
 [2 2]
 [3 3]]
[1 5 1 2 2 3 3]


In [3]:
#array manipulation Routine
x1 = np.arange(16.0).reshape(4, 4)
print('Original Array')
print(x1)

#Horizontol Split
hs=np.hsplit(x1,2)
print('\nHorizontal Split Array')
print(hs)

#Vertical Split
vs=np.vsplit(x1,2)
print('\nVertical Split Array')
print(vs)

#split
s=np.split(x1,4)
print('\nSpliting Array')
print(s)


Original Array
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

Horizontal Split Array
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]

Vertical Split Array
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]

Spliting Array
[array([[0., 1., 2., 3.]]), array([[4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]])]


In [4]:
#String Operations
#Concatenate
#It is used to join two or more strings
x2= np.arange(16,32).reshape(4,4)
print("\nConcatenate Arrays")
print(np.concatenate((x1,x2),axis=None))

s1='HI'
s2='Whats up'
s3=np.concatenate((s1,s2),axis=None)
print(s3)

s4=np.concatenate((s1,x2),axis=None)
print(s4)



Concatenate Arrays
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]
['HI' 'Whats up']
['HI' '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28'
 '29' '30' '31']


In [5]:
#Count
#This function is used to count specific data in an array

cou=np.array(['John', 'OOwen', 'Jacob', 'ChandOler'])
cou1=np.char.count(cou,'o')
print(cou1)

cou2=np.char.count(cou,'O')
print(cou2)

cou3=np.char.count(cou,'O',start=2,end=6)
print(cou3)

[1 0 1 0]
[0 2 0 1]
[0 0 0 1]


In [6]:
#Find
#Find function is used to find a word in an array
find1 = np.array(["Where Is Waldo"])
find2=np.char.find(find1, "Waldo")
print(find2)

find3 = np.array(["Where Is Waldo",'Waldo Is Here'])
find4=np.char.find(find3, "Waldo", start=0 , end=6)
print(find4)
#Here since end is given as 6 first 'Waldo' is found at -1, i.e it started backwards

find5= np.array(["Where Is Waldo",'Waldo Is Here'])
find6=np.char.find(find3, "Waldo", start=0 , end=4)
print(find6)
#Here since end is 4 it shows -1 for second 'Waldo'

[9]
[-1  0]
[-1 -1]


In [7]:
#Comparsion

#Equal
n1=np.array(['xyz','abc','pqr'])
n2=np.array(['XYZ','ABC','PQR'])
n3=np.array(['abc','pqr','xyz'])
n6=np.array(['xyz','abc','pqr'])
n4=np.char.equal(n1,n2)
n5=np.char.equal(n1,n3)
n7=np.char.equal(n1,n6)
print(n4)
#Equal is case sensitive
print(n5)
#For Equal function order is important
print(n7)

#Greater than Less than
n8=np.char.greater(n1,n2)
n9=np.char.greater(n1,n3)
n10=np.char.greater(n1,n6)
print(n8)
#Since n1 consists of small letters and n2 consists of capital laters n1 is greater
print(n9)
#Since in n1 first element in xyz and in n3 it starts with abc it is false and for later abc and pqr is greater than pqr and xyz respectively 
print(n10)
#Since function used is greater and not greater_equal its false

#Greater_equal
n11=np.char.greater_equal(n1,n6)
print(n11)

[False False False]
[False False False]
[ True  True  True]
[ True  True  True]
[ True False False]
[False False False]
[ True  True  True]
